### ISSUE TITLE
Home/Config UI

### ISSUE THREAD

**Issue by RaghavVenkat** [prattheev/ferry#2]

**Comment by prattheev** [comment]
@RaghavVenkat
The Config content are as follows:
#### General :
`Username: ` **String**
`Password: ` **String**
`DeviceId: ` **Integer**

#### Variables :
Note: This must have an add/delete option.
`Variable Name: ` **String**
`Unit: ` **String**
`Parameter No: ` **Integer**

**Comment by prattheev** [comment]
@RaghavVenkat 
Use this Design

![](https://cdn.dribbble.com/users/271837/screenshots/4073411/dropzone-tablet.png)

Fetch the color palette from [here.](https://dribbble.com/shots/4073411-Dropzone-tablet)

**Comment by RaghavVenkat** [comment]
Jquery dynamic add & remove is not working. Code is correct. Pl Check that.
Clikc on config button opens config page in seperate window

**Comment by prattheev** [comment]
I'll take this from here!
